#!/bin/sh /etc/rc.common
# configuration script for zoopig
#MIT license

START=99
STOP=99

PROCESS="zoopig"
DATA_FOLDER="/usr/share/zoopig"
LOG_FILE=$PROCESS"_log"
LOG_FILE_PATH="$DATA_FOLDER/$LOG_FILE"

start(){
	touch $LOG_FILE_PATH
	
	echo "start $PROCESS"
	echo "[$(date)] start process">>$LOG_FILE_PATH
	#lauch application
	echo "run application"
	zoopig &
	echo "[$(date)] run application in background">>$LOG_FILE_PATH
}

stop(){
	echo "[$(date)] stop process">>$LOG_FILE_PATH
	PID="$(pidof $PROCESS)"
	echo "kill $PROCESS"
	echo "$(kill -9 $PID)"
	echo "[$(date)] process killed">>$LOG_FILE_PATH
}
